version: '3'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: